import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic'

// import Title from '../components/Title'
import Title from 'ui/Title'
// const Title = dynamic(() => import('ui/Title'))

const Foo: NextPage = () => {

  return (
    <>
      <Head>
        <title>Foo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title text="Foo" />
        {/* {data && <h3><span style={{ fontWeight: 'bold', color: 'red' }}>Data from API:</span> {JSON.stringify(data)}</h3>} */}
      </main>
    </>
  )
}

Foo.getInitialProps = async () => {
  // const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
  // const data = await res.json();
  return { };
}

export default Foo