import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic'
import Link from 'next/link'
import { ChakraProvider } from '@chakra-ui/react'
// @ts-ignore
import theme from 'ui/theme'


import HomeTitle from '../components/Title'
import UiTitle from 'ui/Title'
// import Counter from 'ui/Counter'
// import useStore from 'ui/store'
// const Title = dynamic(() => import('ui/Title'))

const Home: NextPage = ({ data }: any) => {

  // const {Pop} = NavComp
  // const {count, increment, decrement} = useStore()

  return (
    <>
      {/* <ChakraProvider resetCSS theme={theme}> */}

        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <HomeTitle text="Home" />
          <UiTitle text="Home" />
          {/* <Pop text="Home" /> */}
          {/* <Title text="Home" /> */}
          {/* <Counter count={count} onIncrement={increment} onDecrement={decrement} /> */}
          {data && <h3><span style={{ fontWeight: 'bold' }}>Data from API:</span> {JSON.stringify(data)}</h3>}
        </main>
      {/* </ChakraProvider> */}
    </>
  )
}

Home.getInitialProps = async () => {
  // const NavComp = (await import('ui/Nav')).default
  const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
  const data = await res.json();
  return { data };
}

export default Home