import type { NextPage } from 'next'
import Head from 'next/head'

// const Title = dynamic(() => import('ui/Title'))
import Title from 'ui/Title'
import Layout from 'ui/Layout'

const Other: NextPage = ({ data }: any) => {
  return (
    <>
      <Head>
        <title>OTHER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Title text="Other" /> */}
        {/* <Counter count={count} onIncrement={increment} onDecrement={decrement} /> */}
        <Layout>
          <Title text="Other s" />
        </Layout>
        {data && <h3><span style={{ fontWeight: 'bold' }}>Data from API:</span> {JSON.stringify(data)}</h3>}
      </main>
    </>
  )
}

Other.getInitialProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
  const data = await res.json();
  return { data };
}

export default Other