import type { NextPage } from 'next'
import Head from 'next/head'


const Shell: NextPage = () => {

  return (
    <>
      <Head>
        <title>Shell</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Shell
        </h1>
        <br />
      </main>
    </>
  )
}

Shell.getInitialProps = async (ctx) => {
  return { ctx };
}

export default Shell
