import type { NextPage } from 'next'
import Head from 'next/head'

import Title from 'ui/Title'
import Counter from 'ui/Counter'
import useStore from 'ui/store'

const Faq: NextPage = ({ data }: any) => {
  const {count, increment, decrement} = useStore()

  return (
    <>
      <Head>
        <title>FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title text="FAQ" />
        <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        {data && <h3><span style={{ fontWeight: 'bold', color: 'green'  }}>Data from API:</span> {JSON.stringify(data, null, 2)}</h3>}
      </main>
    </>
  )
}

Faq.getInitialProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
  const data = await res.json();
  return { data };
}

export default Faq